# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\x12\x07weather\"\"\n\x0eWeatherRequest\x12\x10\n\x08location\x18\x01 \x01(\t\"]\n\x0fWeatherResponse\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\t\x12\x11\n\tcondition\x18\x03 \x01(\t\x12\x10\n\x08humidity\x18\x04 \x01(\t2Q\n\x0eWeatherService\x12?\n\nGetWeather\x12\x17.weather.WeatherRequest\x1a\x18.weather.WeatherResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEATHERREQUEST']._serialized_start=26
  _globals['_WEATHERREQUEST']._serialized_end=60
  _globals['_WEATHERRESPONSE']._serialized_start=62
  _globals['_WEATHERRESPONSE']._serialized_end=155
  _globals['_WEATHERSERVICE']._serialized_start=157
  _globals['_WEATHERSERVICE']._serialized_end=238
# @@protoc_insertion_point(module_scope)
